// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtj5V28zjvHcv2cLUPSc0q4N4C7sSzZqA',
    appId: '1:1065156611010:web:229378452d635316a0245b',
    messagingSenderId: '1065156611010',
    projectId: 'taskgi',
    authDomain: 'taskgi.firebaseapp.com',
    storageBucket: 'taskgi.firebasestorage.app',
    measurementId: 'G-JFVL897LWJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATUra9-qNrMyPAbOj_otPbmzKlCxmtiYE',
    appId: '1:1065156611010:android:3b413fb69653a89ea0245b',
    messagingSenderId: '1065156611010',
    projectId: 'taskgi',
    storageBucket: 'taskgi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQ_YZX69FPId48w5MrOjOFiMbUI4il7LA',
    appId: '1:1065156611010:ios:c54c833c0228cf4ba0245b',
    messagingSenderId: '1065156611010',
    projectId: 'taskgi',
    storageBucket: 'taskgi.firebasestorage.app',
    iosBundleId: 'com.example.taskgi',
  );
}
